Text Cleaning

In [1]:
text='I am learning natural language processing.I am fond of it. I like career in same field'
text

'I am learning natural language processing.I am fond of it. I like career in same field'

In [2]:
import nltk

C:\Users\keert\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\keert\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\keert\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
C:\Users\keert\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [12]:
nltk.tokenize.sent_tokenize(text)


['I am learning natural language processing.I am fond of it.',
 'I like career in same field']

In [13]:
# import nltk
# nltk.download('punkt')

In [15]:
nltk.tokenize.word_tokenize(text)

['I',
 'am',
 'learning',
 'natural',
 'language',
 'processing.I',
 'am',
 'fond',
 'of',
 'it',
 '.',
 'I',
 'like',
 'career',
 'in',
 'same',
 'field']

In [16]:
my_stopwords= ['i','am','for','the']

In [17]:
clean_text= [word for word in nltk.tokenize.word_tokenize(text.lower()) if word not in my_stopwords]
clean_text

['learning',
 'natural',
 'language',
 'processing.i',
 'fond',
 'of',
 'it',
 '.',
 'like',
 'career',
 'in',
 'same',
 'field']

In [25]:
from nltk.corpus import stopwords
mystop=stopwords.words('english')
print(mystop)
# stopwords.words('english')

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [21]:
# nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\keert\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [26]:
'3'.isdigit()

True

STEMMING --process of removing suffix
AND LEMMATIZATION-- grouping together the inflected forms of a word so they can be analysed as a single item

In [28]:
from nltk.stem import PorterStemmer
stemmer=PorterStemmer()

In [29]:
stemmer.stem('policy')

'polici'

In [32]:
stemmer.stem('buying')

'buy'

In [54]:
from nltk.stem import  WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [41]:
lemmatizer.lemmatize('better',pos='n') #PartofSpeech assign

'better'

In [40]:
# nltk.download('wordnet')
# nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\keert\AppData\Roaming\nltk_data...


True

In [42]:
lemmatizer.lemmatize('better',pos='a') #PartofSpeech assign  adjective

'good'

In [43]:
lemmatizer.lemmatize('better')

'better'

In [144]:
import spacy
nlp = spacy.load("en_core_web_sm")

OSError: [E053] Could not read config file from C:\Users\keert\anaconda3\lib\site-packages\en_core_web_sm\en_core_web_sm-2.2.0\config.cfg

In [53]:
# pip install spacy
# python3 -m spacy download en_core_web_sm
# pip3 install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz

SyntaxError: invalid syntax (3852703900.py, line 2)

In [56]:
import re

In [57]:
re.findall('abc','abc is a great boy. so what')

['abc']

In [58]:
re.findall('abcd','abc is a great boy. so what')

[]

In [64]:
re.findall('abcd','abcde is a great boy. so what ABCd')

['abcd']

In [63]:
re.search('abcd','abcde is a great boy. so what abcd')

<re.Match object; span=(0, 4), match='abcd'>

In [65]:
'abcde is a great boy. so what abcd'[0:4]

'abcd'

In [68]:
list(re.finditer('abcd','abcde is a great boy. so what abcd'))

[<re.Match object; span=(0, 4), match='abcd'>,
 <re.Match object; span=(30, 34), match='abcd'>]

In [69]:
list(range(1,4))

[1, 2, 3]

In [70]:
range(1,4)

range(1, 4)

In [72]:
'abcd is a great boy. so what abcd'.split().count('abcd')

2

In [73]:
re.sub('abcd','xyz','abcde is a great boy. so what abcd')

'xyze is a great boy. so what xyz'

In [75]:
match=re.compile('abcd') #compile the match in object)

In [77]:
match.search('abcde is a great boy. so what abcd')

<re.Match object; span=(0, 4), match='abcd'>

In [78]:
match.sub('xyz','abcde is a great boy. so what abcd')

'xyze is a great boy. so what xyz'

In [80]:
list(match.finditer('abcde is a great boy. so what abcd'))

[<re.Match object; span=(0, 4), match='abcd'>,
 <re.Match object; span=(30, 34), match='abcd'>]

In [103]:
match=re.compile('.') # dot means capture anything

In [105]:
list(match.finditer('abcde is a great boy. so what abcd.'))

[<re.Match object; span=(0, 1), match='a'>,
 <re.Match object; span=(1, 2), match='b'>,
 <re.Match object; span=(2, 3), match='c'>,
 <re.Match object; span=(3, 4), match='d'>,
 <re.Match object; span=(4, 5), match='e'>,
 <re.Match object; span=(5, 6), match=' '>,
 <re.Match object; span=(6, 7), match='i'>,
 <re.Match object; span=(7, 8), match='s'>,
 <re.Match object; span=(8, 9), match=' '>,
 <re.Match object; span=(9, 10), match='a'>,
 <re.Match object; span=(10, 11), match=' '>,
 <re.Match object; span=(11, 12), match='g'>,
 <re.Match object; span=(12, 13), match='r'>,
 <re.Match object; span=(13, 14), match='e'>,
 <re.Match object; span=(14, 15), match='a'>,
 <re.Match object; span=(15, 16), match='t'>,
 <re.Match object; span=(16, 17), match=' '>,
 <re.Match object; span=(17, 18), match='b'>,
 <re.Match object; span=(18, 19), match='o'>,
 <re.Match object; span=(19, 20), match='y'>,
 <re.Match object; span=(20, 21), match='.'>,
 <re.Match object; span=(21, 22), match=' '>,
 <re.Ma

In [88]:
match.search('abcde is a great boy. so what abcd')

<re.Match object; span=(0, 1), match='a'>

In [89]:
#Remove . from a string

In [90]:
print('\tto you')

	to you


In [91]:
print('\\tto you')  #back slash is escape character

\tto you


In [92]:
re.sub('.','x','yo man.wassup.')

'xxxxxxxxxxxxxx'

In [93]:
re.sub('\.','x','yo man.wassup.')

'yo manxwassupx'

In [95]:
re.sub('Y|y.','x','Yo man.wassup you.') #Or character |

'xo man.wassup xu.'

In [100]:
re.sub('\+','','yo man.I have 5+ year exp.')   # + is special cahracter. ! - are not

'yo man.I have 5 year exp.'

In [101]:
re.sub('\!','','yo man!!!I have 5+ year exp.')

'yo manI have 5+ year exp.'

In [107]:
re.findall('\.', 'yo man.wassup.')

['.', '.']

In [110]:
re.findall('/', 'https://yo man.wassup.')

['/', '/']

In [112]:
print('\wassup')

\wassup


In [116]:
print('\nwass\nsup')


wass
sup


In [114]:
print(r'\nwass\nsup') # include r to say dont consider them as special chars

\nwas\nsup


In [137]:
sentence='In film, television, and theatre, typecasting is the process 5+ 6- by which a particular actor becomes strongly identified with a specific character, one or more particular roles, or characters having the same traits or coming from the same social or ethnic groups.'

In [142]:
# pattern=re.compile(r'.') #capture anything
# pattern=re.compile(r'\.')
pattern=re.compile(r'\d') #capture all digits
# pattern=re.compile(r'\D') #capture all non  digits
# pattern=re.compile(r'\w') #A-z 0-9 _
# pattern=re.compile(r'\W')
# pattern=re.compile(r'\s') #capture all white spaces
# pattern=re.compile(r'\S')
# pattern=re.compile(r'[A-Z]') #upper case 
# pattern=re.compile(r'[a-z]')
# pattern=re.compile(r'[A-z]') #all cases


In [143]:
matches = pattern.finditer(sentence)
for match in matches:
    print(match)

<re.Match object; span=(61, 62), match='5'>
<re.Match object; span=(64, 65), match='6'>


In [154]:
sentence1='In film, television, and theatre, typecasting is the process 5+ 6- by which a particular actor becomes strongly.'
sentence2=' theatre, typecasting is the process 5+ 6- by which a particular actor becomes strongly'


^ start of sentence
$ end of string

In [155]:
pattern=re.compile(r'^[A-Z]')

In [156]:
matches = pattern.finditer(sentence1)
for match in matches:
    print(match)

<re.Match object; span=(0, 1), match='I'>


In [157]:
matches = pattern.finditer(sentence2)
for match in matches:
    print(match)

In [158]:
pattern=re.compile(r'.$')
matches = pattern.finditer(sentence1)
for match in matches:
    print(match)

<re.Match object; span=(111, 112), match='.'>


In [179]:
sentences=['I am good','I am sad','you are good','3789 is my pin']


In [182]:
def replacefun(SeriesofSent, FStartEnd,Char1, Char2):
    sentences1=[]
    if FStartEnd=='Start':
        pattern1='^'+Char1
    else:
        pattern1=Char1+'$'
    pattern=re.compile(pattern1)  
    for a in SeriesofSent:
        # print(a)
        sentences1.append(pattern.sub(Char2,a))
        # print(sentences1)
    return sentences1
       
    

In [183]:
replacefun(sentences, 'Start','[A-Z]','XYZ')

['XYZ am good', 'XYZ am sad', 'you are good', '3789 is my pin']

In [184]:
replacefun(sentences, 'Start','[0-9]','XYZ')

['I am good', 'I am sad', 'you are good', 'XYZ789 is my pin']

In [203]:
sentences='''123-456-6788
343-543-3555
345-355-5555'''


In [198]:
# pattern=re.compile('\d')
pattern=re.compile('\d\d\d\d')
# pattern=re.compile('\d\d\d.')
# pattern=re.compile('\d')
# pattern=re.compile('\d\d\d-\d\d\d-\d\d\d\d')

In [205]:

matches=pattern.finditer(sentences)
for match in matches:
    print(match)

<re.Match object; span=(0, 12), match='123-456-6788'>
<re.Match object; span=(13, 25), match='343-543-3555'>
<re.Match object; span=(26, 38), match='345-355-5555'>


In [206]:
pattern=re.compile('\d\d\d-\d\d\d-\d\d\d\d')

matches=pattern.finditer(sentences)
for match in matches:
    print(match)

<re.Match object; span=(0, 12), match='123-456-6788'>
<re.Match object; span=(13, 25), match='343-543-3555'>
<re.Match object; span=(26, 38), match='345-355-5555'>


In [210]:
pattern=re.compile('\d\d\d')

matches=pattern.finditer(sentences)
for match in matches:
    print(match)

<re.Match object; span=(0, 3), match='123'>
<re.Match object; span=(4, 7), match='456'>
<re.Match object; span=(8, 11), match='678'>
<re.Match object; span=(13, 16), match='343'>
<re.Match object; span=(17, 20), match='543'>
<re.Match object; span=(21, 24), match='355'>
<re.Match object; span=(26, 29), match='345'>
<re.Match object; span=(30, 33), match='355'>
<re.Match object; span=(34, 37), match='555'>


In [220]:
sentences='''123-456-6788
343-543-3555
345-355-5555'''


In [222]:
pattern=re.compile('\d\d\d$')

In [221]:
matches=pattern.finditer(sentences)

for match in matches:
    print(match)

<re.Match object; span=(35, 38), match='555'>


In [218]:
sentences='''123-456-6788
343-543-3555
345-355-5555'''


In [223]:
pattern=re.compile('\d\d\d$')
pattern.sub('YYY',sentences)

'123-456-6788\n343-543-3555\n345-355-5YYY'

In [214]:
def replacefun(SeriesofSent, FStartEnd,Char1, Char2):
    sentences1=[]
    if FStartEnd=='Start':
        pattern1='^'+Char1
    else:
        pattern1=Char1+'$'
    pattern=re.compile(pattern1)  
    if  
    
    for a in SeriesofSent:
        # print(a)
        sentences1.append(pattern.sub(Char2,a))
        # print(sentences1)
    return sentences1
       
    

In [215]:
replacefun(sentences, 'End','[A-Z]','XYZ')

['1',
 '2',
 '3',
 '-',
 '4',
 '5',
 '6',
 '-',
 '6',
 '7',
 '8',
 '8',
 '\n',
 '3',
 '4',
 '3',
 '-',
 '5',
 '4',
 '3',
 '-',
 '3',
 '5',
 '5',
 '5',
 '\n',
 '3',
 '4',
 '5',
 '-',
 '3',
 '5',
 '5',
 '-',
 '5',
 '5',
 '5',
 '5']

In [224]:
sentences='''123-456-6788
343-543-3555
345-355-5555'''

In [226]:
pattern=re.compile('\w\w\w')
matches=pattern.finditer(sentences)

for match in matches:
    print(match)

<re.Match object; span=(0, 3), match='123'>
<re.Match object; span=(4, 7), match='456'>
<re.Match object; span=(8, 11), match='678'>
<re.Match object; span=(13, 16), match='343'>
<re.Match object; span=(17, 20), match='543'>
<re.Match object; span=(21, 24), match='355'>
<re.Match object; span=(26, 29), match='345'>
<re.Match object; span=(30, 33), match='355'>
<re.Match object; span=(34, 37), match='555'>


In [266]:
sentences='''
    vin.kal@gmail.com 
    aks.45@yahoo.com
    mahira.kalakuntla@hotmail.com
'''

In [267]:
re.search('\w\w\w.\w\w\w@gmail.com',sentences)

<re.Match object; span=(5, 22), match='vin.kal@gmail.com'>

In [268]:
re.search('a\w\w.\d\d@yahoo.com','aks.45@yahoo.com')
# re.search('a\w\w.\d\d@yahoo.com',sentences)

<re.Match object; span=(0, 16), match='aks.45@yahoo.com'>

In [269]:
re.search('@\w\w\w',sentences)

<re.Match object; span=(12, 16), match='@gma'>

In [285]:
sentences='''
    323-449-2347 vin.kal@gmail.com 
    +1-303-445-2377  aks.45@yahoo.com
    31-449-234  mahira.kalakuntla@hotmail.com
'''

In [276]:
re.search('\+\d-\d\d\d-\d\d\d-\d\d\d\d',sentences)

<re.Match object; span=(41, 56), match='+1-303-445-2377'>

In [278]:
re.search('\+\d-\d{3}-\d{3}-\d{4}',sentences)

<re.Match object; span=(41, 56), match='+1-303-445-2377'>

In [281]:
list(re.finditer('\+\d-\d{2,4}-\d{3}-\d{4}',sentences))

[<re.Match object; span=(41, 56), match='+1-303-445-2377'>]

In [288]:
list(re.finditer('\d{1,4}-\d{3}-\d{3,4}',sentences))

[<re.Match object; span=(5, 17), match='323-449-2347'>,
 <re.Match object; span=(42, 51), match='1-303-445'>,
 <re.Match object; span=(79, 89), match='31-449-234'>]

In [290]:
sentences='''
    323-449-2347 vin.kal@gmail.com 
    +1-303-445-2377  aks.45@yahoo.com
    31-449-234  mahira.kalakuntla@hotmail.com
    31-449.234
'''

In [291]:
list(re.finditer('.\d{1,4}[-.]\d{3}[-.]\d{3,4}',sentences))  #[-.] means - or .

[<re.Match object; span=(4, 17), match=' 323-449-2347'>,
 <re.Match object; span=(41, 51), match='+1-303-445'>,
 <re.Match object; span=(78, 89), match=' 31-449-234'>,
 <re.Match object; span=(124, 135), match=' 31-449.234'>]

In [ ]:
list(re.finditer('.\d{1,4}[-.]\d{3}[-.]\d{3,4}',sentences))  #[-.] means - or .

In [296]:
sentences='''
    323-449-2347 vin.kal@gmail.com 
    +1-303-445-2377  aks.45@yahoo.com
    32331-449-234  mahira.kalakuntla@hotmail.com
    31-449.234
    -449.234
'''

In [297]:
list(re.finditer('.\d+[-.]\d{3}[-.]\d{3,4}',sentences))  #[-.] means - or .

[<re.Match object; span=(4, 17), match=' 323-449-2347'>,
 <re.Match object; span=(41, 51), match='+1-303-445'>,
 <re.Match object; span=(78, 92), match=' 32331-449-234'>,
 <re.Match object; span=(127, 138), match=' 31-449.234'>]

In [300]:
list(re.finditer('\d*[-.]\d{3}[-.]\d{3,4}',sentences))  #[-.] means - or .

[<re.Match object; span=(5, 17), match='323-449-2347'>,
 <re.Match object; span=(42, 51), match='1-303-445'>,
 <re.Match object; span=(79, 92), match='32331-449-234'>,
 <re.Match object; span=(128, 138), match='31-449.234'>,
 <re.Match object; span=(143, 151), match='-449.234'>]

In [301]:
list(re.finditer('\+?\d*[-.]\d{3}[-.]\d{3,4}',sentences))  #lets include +1 also... ? mean 0 or 1

[<re.Match object; span=(5, 17), match='323-449-2347'>,
 <re.Match object; span=(41, 51), match='+1-303-445'>,
 <re.Match object; span=(79, 92), match='32331-449-234'>,
 <re.Match object; span=(128, 138), match='31-449.234'>,
 <re.Match object; span=(143, 151), match='-449.234'>]

In [309]:
sentences='''
    323-449-2347 vin.kal@gmail.com 
    +1-303-445-2377  aks.45@yahoo.com
    32331-449-234  mahira.kalakuntla@hotmail.com
    31-449.234 mahir_untla@hotmail.com
    -449.234  _@jhg.com
'''

In [312]:
# list(re.finditer('\+?\d*[-.]\d{3}[-.]\d{3,4}',sentences))  
list(re.finditer('\w*\.?\w*@\w*.com',sentences))  

[<re.Match object; span=(18, 35), match='vin.kal@gmail.com'>,
 <re.Match object; span=(58, 74), match='aks.45@yahoo.com'>,
 <re.Match object; span=(94, 123), match='mahira.kalakuntla@hotmail.com'>,
 <re.Match object; span=(139, 162), match='mahir_untla@hotmail.com'>,
 <re.Match object; span=(177, 186), match='_@jhg.com'>]

In [313]:
# _@ is not valid so try below 

list(re.finditer('[a-zA-Z]+[.\w]+@[\w]+.[a-z]{2,}',sentences))  # now, the invalid email is removed

[<re.Match object; span=(18, 35), match='vin.kal@gmail.com'>,
 <re.Match object; span=(58, 74), match='aks.45@yahoo.com'>,
 <re.Match object; span=(94, 123), match='mahira.kalakuntla@hotmail.com'>,
 <re.Match object; span=(139, 162), match='mahir_untla@hotmail.com'>]

In [314]:
pattern=re.compile('[a-zA-Z]+[.\w]+@[\w]+.[a-z]{2,}')
matches=pattern.finditer(sentences)

for match in matches:
    print(match)

<re.Match object; span=(18, 35), match='vin.kal@gmail.com'>
<re.Match object; span=(58, 74), match='aks.45@yahoo.com'>
<re.Match object; span=(94, 123), match='mahira.kalakuntla@hotmail.com'>
<re.Match object; span=(139, 162), match='mahir_untla@hotmail.com'>


In [321]:
# list(re.finditer('Mr.[\s\w]+',sentence)) 

[<re.Match object; span=(5, 52), match='Mr. Michael\n    Mr Smith\n    Ms Kritika\n    Mr>,
 <re.Match object; span=(69, 81), match='Mr. T\n    Ms'>]

In [338]:
# Capture male and female seperately

sentence = '''
    Mr. Michael
    Mr Smith
    Ms Kritika
    Mrs. Jacqueline
    Mr. T
    Ms. Leena
    '''




In [339]:
pattern=re.compile('Mr\.?\s[A-Z][a-z]*')
matchesMale=pattern.finditer(sentence)

for match in matchesMale:
    print(match)

<re.Match object; span=(5, 16), match='Mr. Michael'>
<re.Match object; span=(21, 29), match='Mr Smith'>
<re.Match object; span=(69, 74), match='Mr. T'>


In [344]:
phonenumbers = '''
    0091 91919345
    +4 12093487
    092 7832109 (40)
    00966-5021842
'''


In [357]:
pattern=re.compile('(09|009|\+)\d*[\s-]\d*')  #my ans
matchesMale=pattern.finditer(phonenumbers)

for match in matchesMale:
    print(match)

<re.Match object; span=(5, 18), match='0091 91919345'>
<re.Match object; span=(23, 34), match='+4 12093487'>
<re.Match object; span=(39, 50), match='092 7832109'>
<re.Match object; span=(60, 73), match='00966-5021842'>


In [376]:
pattern=re.compile('(\+?\d+)[\s-]?(\d+)(\s\(\d{2}\))?')
matchesMale=pattern.finditer(phonenumbers)

for match in matchesMale:
    print(match[1],match[2],match[3])     #country code,ph number, extension

0091 91919345 None
+4 12093487 None
092 7832109  (40)
00966 5021842 None


In [335]:
pattern=re.compile('M(rs|s)\.?\s[A-Z][a-z]+')
matchesF=pattern.finditer(sentence)

for match in matchesF:
    print(match)

<re.Match object; span=(34, 44), match='Ms Kritika'>
<re.Match object; span=(49, 64), match='Mrs. Jacqueline'>
<re.Match object; span=(79, 88), match='Ms. Leena'>


In [336]:
pattern=re.compile('M(rs|s)\.?\s[A-Z]\w+')
matchesF=pattern.finditer(sentence)

for match in matchesF:
    print(match)

<re.Match object; span=(34, 44), match='Ms Kritika'>
<re.Match object; span=(49, 64), match='Mrs. Jacqueline'>
<re.Match object; span=(79, 88), match='Ms. Leena'>


In [337]:
list(re.finditer('[^App]', 'Apple a day keeps away'))  #exxclude App

[<re.Match object; span=(3, 4), match='l'>,
 <re.Match object; span=(4, 5), match='e'>,
 <re.Match object; span=(5, 6), match=' '>,
 <re.Match object; span=(6, 7), match='a'>,
 <re.Match object; span=(7, 8), match=' '>,
 <re.Match object; span=(8, 9), match='d'>,
 <re.Match object; span=(9, 10), match='a'>,
 <re.Match object; span=(10, 11), match='y'>,
 <re.Match object; span=(11, 12), match=' '>,
 <re.Match object; span=(12, 13), match='k'>,
 <re.Match object; span=(13, 14), match='e'>,
 <re.Match object; span=(14, 15), match='e'>,
 <re.Match object; span=(16, 17), match='s'>,
 <re.Match object; span=(17, 18), match=' '>,
 <re.Match object; span=(18, 19), match='a'>,
 <re.Match object; span=(19, 20), match='w'>,
 <re.Match object; span=(20, 21), match='a'>,
 <re.Match object; span=(21, 22), match='y'>]

Raw Text -- Cleaning and pre processing -- tokenisation -- text transformation(bridge between NLP and  AI ML) -- modelling -- evaluation

ONE HOT representation of string

['dog', 'bites', 'man']


In [380]:
vocab={dog: 0 ,bites: 1 ,man: 2 }

NameError: name 'dog' is not defined

In [404]:
def my_func(a):
    vocab={}
    count=0
    
    for stat in a:
        for word in stat.split():
            if word not in vocab:
                vocab[word.lower()] =count
                count=count+1
    return vocab

    onehotencoded=[]
            

In [405]:
my_func(['dog bites man','man bites dog'])

{'dog': 0, 'bites': 1, 'man': 2}

In [450]:
def get_ohe(list_of_strings):
    vocab = {}
    count=0
    for i in list_of_strings:
        for word in i.split():
            if word.lower() not in vocab:
                vocab[word.lower()]=count
                count = count + 1
    onehotencoded_sent=[] 
    for sentences in list_of_strings:                   
        onehotencoded_words = []
        for word in sentences.split():
            temp = [0]*len(vocab)
            
            if word.lower() in vocab:
                temp[vocab[word.lower()]] = 1
                # print(vocab[word.lower()])
                print(temp)
            onehotencoded_words.extend(temp)
            # print(word ,  onehotencoded_words)
        onehotencoded_sent.append(onehotencoded_words)
            
    return vocab,   list(zip(list_of_strings,onehotencoded_sent))








In [451]:
get_ohe(['dog bites man','man bites dog'])

[1, 0, 0]
[0, 1, 0]
[0, 0, 1]
[0, 0, 1]
[0, 1, 0]
[1, 0, 0]


({'dog': 0, 'bites': 1, 'man': 2},
 [('dog bites man', [1, 0, 0, 0, 1, 0, 0, 0, 1]),
  ('man bites dog', [0, 0, 1, 0, 1, 0, 1, 0, 0])])

In [443]:
vocab = {'dog':0, 'bites':1 , 'man':2, 'eats': 3, 'meat' :4}

In [456]:
def get_bow(list_of_strings):
    vocab = {}
    count=0
    for i in list_of_strings:
        for word in i.split():
            if word.lower() not in vocab:
                vocab[word.lower()]=count
                count = count + 1
    onehotencoded_sent=[] 
    for sentences in list_of_strings:                   
        # onehotencoded_words = []
        temp = [0]*len(vocab)
        for word in sentences.split():
            if word.lower() in vocab:
                temp[vocab[word.lower()]]+= 1
                
        onehotencoded_sent.append(temp)
            
    return vocab,   list(zip(list_of_strings,onehotencoded_sent))








In [457]:
get_bow(['dog bites man','man bites dog'])

({'dog': 0, 'bites': 1, 'man': 2},
 [('dog bites man', [1, 1, 1]), ('man bites dog', [1, 1, 1])])



## Ready made function of bag of words (BOW)

In [503]:
my_corpus=(['dog bites man. man is kind to dog','man bites dog. god loves man','Dog and man are friends. dog is kind man'])

In [519]:
from sklearn.feature_extraction.text import CountVectorizer

In [520]:
my_vectorizer=CountVectorizer()


In [512]:

my_vectorizer_rep= my_vectorizer.fit_transform(my_corpus)

In [513]:
my_vectorizer.vocabulary_

{'dog': 3,
 'bites': 2,
 'man': 9,
 'is': 6,
 'kind': 7,
 'to': 10,
 'god': 5,
 'loves': 8,
 'and': 0,
 'are': 1,
 'friends': 4}

In [514]:
my_vectorizer.transform(['Dog are friends']).toarray()

array([[0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [515]:
my_vectorizer.transform(my_corpus).toarray()

array([[0, 0, 1, 2, 0, 0, 1, 1, 0, 2, 1],
       [0, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0],
       [1, 1, 0, 2, 1, 0, 1, 1, 0, 2, 0]], dtype=int64)

In [516]:
list(zip(my_corpus, my_vectorizer.transform(my_corpus).toarray()))

[('dog bites man. man is kind to dog',
  array([0, 0, 1, 2, 0, 0, 1, 1, 0, 2, 1], dtype=int64)),
 ('man bites dog. god loves man',
  array([0, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0], dtype=int64)),
 ('Dog and man are friends. dog is kind man',
  array([1, 1, 0, 2, 1, 0, 1, 1, 0, 2, 0], dtype=int64))]

In [518]:
my_vectorizer_rep[2].toarray()

array([[1, 1, 0, 2, 1, 0, 1, 1, 0, 2, 0]], dtype=int64)

## If we are looking only for present of word, use binary = true

In [524]:
my_corpus=(['dog bites man. man is kind to dog','man bites dog. god loves man','Dog and man are friends. dog is kind man'])

In [525]:
from sklearn.feature_extraction.text import CountVectorizer

In [526]:
my_vectorizer=CountVectorizer(binary=True)


In [527]:

my_vectorizer_rep= my_vectorizer.fit_transform(my_corpus)

In [528]:
my_vectorizer.vocabulary_

{'dog': 3,
 'bites': 2,
 'man': 9,
 'is': 6,
 'kind': 7,
 'to': 10,
 'god': 5,
 'loves': 8,
 'and': 0,
 'are': 1,
 'friends': 4}

In [529]:
my_vectorizer.transform(['Dog are friends']).toarray()

array([[0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [530]:
my_vectorizer.transform(my_corpus).toarray()

array([[0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0]], dtype=int64)

In [531]:
list(zip(my_corpus, my_vectorizer.transform(my_corpus).toarray()))

[('dog bites man. man is kind to dog',
  array([0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1], dtype=int64)),
 ('man bites dog. god loves man',
  array([0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0], dtype=int64)),
 ('Dog and man are friends. dog is kind man',
  array([1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0], dtype=int64))]

# Ngrams   - Ngrams capture context by capturing adjecent words 


In [540]:
import nltk

In [532]:
list(nltk.ngrams(nltk.tokenize.word_tokenize('I am Happy'),n=2))

[('I', 'am'), ('am', 'Happy')]

In [535]:


list(nltk.ngrams(nltk.tokenize.word_tokenize(' This page should work with any browser that obeys the DOM, and Internet Explorer'),n=4))

[('This', 'page', 'should', 'work'),
 ('page', 'should', 'work', 'with'),
 ('should', 'work', 'with', 'any'),
 ('work', 'with', 'any', 'browser'),
 ('with', 'any', 'browser', 'that'),
 ('any', 'browser', 'that', 'obeys'),
 ('browser', 'that', 'obeys', 'the'),
 ('that', 'obeys', 'the', 'DOM'),
 ('obeys', 'the', 'DOM', ','),
 ('the', 'DOM', ',', 'and'),
 ('DOM', ',', 'and', 'Internet'),
 (',', 'and', 'Internet', 'Explorer')]

In [541]:
my_corpus=(['dog bites man. man is kind to dog','man bites dog. god loves man','Dog and man are friends. dog is kind man'])

In [554]:
my_vectorizer=CountVectorizer(ngram_range=(1,3))

my_vectorizer_rep= my_vectorizer.fit_transform(my_corpus)

my_vectorizer.vocabulary_

{'dog': 11,
 'bites': 6,
 'man': 36,
 'is': 26,
 'kind': 30,
 'to': 45,
 'dog bites': 14,
 'bites man': 9,
 'man man': 43,
 'man is': 41,
 'is kind': 27,
 'kind to': 32,
 'to dog': 46,
 'dog bites man': 15,
 'bites man man': 10,
 'man man is': 44,
 'man is kind': 42,
 'is kind to': 29,
 'kind to dog': 33,
 'god': 23,
 'loves': 34,
 'man bites': 39,
 'bites dog': 7,
 'dog god': 16,
 'god loves': 24,
 'loves man': 35,
 'man bites dog': 40,
 'bites dog god': 8,
 'dog god loves': 17,
 'god loves man': 25,
 'and': 0,
 'are': 3,
 'friends': 20,
 'dog and': 12,
 'and man': 1,
 'man are': 37,
 'are friends': 4,
 'friends dog': 21,
 'dog is': 18,
 'kind man': 31,
 'dog and man': 13,
 'and man are': 2,
 'man are friends': 38,
 'are friends dog': 5,
 'friends dog is': 22,
 'dog is kind': 19,
 'is kind man': 28}

In [553]:
my_vectorizer.transform(['Dog and man are dog with dog']).toarray()

array([[1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [558]:
my_vectorizer.transform(['Dog bites man','man bites dog']).toarray()  # see here the arrays are different - captured as different arrays. 
#In BOW, you will see same representation of arrays but NGram fied this issue by taking adjacent words- context

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0]], dtype=int64)


## TfIdf  imp of word considered  compared to other words 

In [561]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [562]:
tfidf=TfidfVectorizer()

In [578]:
my_corpus=(['dog bites man great. man is kind to dog','man bites dog. god loves man','Dog and man are friends. dog is kind man'])

In [579]:
tfidf.fit_transform(my_corpus)

<3x12 sparse matrix of type '<class 'numpy.float64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [580]:
tfidf.get_feature_names() #words in vocab 

['and',
 'are',
 'bites',
 'dog',
 'friends',
 'god',
 'great',
 'is',
 'kind',
 'loves',
 'man',
 'to']

In [588]:
list(zip(tfidf.get_feature_names() ,tfidf.idf_))  #below is idf score -this is common for all docs)

[('and', 1.6931471805599454),
 ('are', 1.6931471805599454),
 ('bites', 1.2876820724517808),
 ('dog', 1.0),
 ('friends', 1.6931471805599454),
 ('god', 1.6931471805599454),
 ('great', 1.6931471805599454),
 ('is', 1.2876820724517808),
 ('kind', 1.2876820724517808),
 ('loves', 1.6931471805599454),
 ('man', 1.0),
 ('to', 1.6931471805599454)]

In [581]:
tfidf.idf_   #score of words in vocabulary  #man has lowest weightage as it is present in all sentences. and appeared only one sentence so high weightage

array([1.69314718, 1.69314718, 1.28768207, 1.        , 1.69314718,
       1.69314718, 1.69314718, 1.28768207, 1.28768207, 1.69314718,
       1.        , 1.69314718])

In [582]:
tfidf.vocabulary_

{'dog': 3,
 'bites': 2,
 'man': 10,
 'great': 6,
 'is': 7,
 'kind': 8,
 'to': 11,
 'god': 5,
 'loves': 9,
 'and': 0,
 'are': 1,
 'friends': 4}

In [583]:
tfidf.fit_transform(my_corpus).toarray()   

array([[0.        , 0.        , 0.29771209, 0.4624    , 0.        ,
        0.        , 0.39145563, 0.29771209, 0.29771209, 0.        ,
        0.4624    , 0.39145563],
       [0.        , 0.        , 0.36580076, 0.28407693, 0.        ,
        0.48098405, 0.        , 0.        , 0.        , 0.48098405,
        0.56815385, 0.        ],
       [0.3793921 , 0.3793921 , 0.        , 0.44815017, 0.3793921 ,
        0.        , 0.        , 0.28853747, 0.28853747, 0.        ,
        0.44815017, 0.        ]])

In [584]:
tfidf.fit_transform(my_corpus)[0].toarray()  #belongs to 'dog bites man. man is kind to dog'    #these are tfidf scores

array([[0.        , 0.        , 0.29771209, 0.4624    , 0.        ,
        0.        , 0.39145563, 0.29771209, 0.29771209, 0.        ,
        0.4624    , 0.39145563]])

In [585]:
list(zip(my_corpus,tfidf.transform(my_corpus).toarray() ))  ## and, are-- are have 0 occurances and hence seeing 0. great is only present once - rare .. so high Tfidf

[('dog bites man great. man is kind to dog',
  array([0.        , 0.        , 0.29771209, 0.4624    , 0.        ,
         0.        , 0.39145563, 0.29771209, 0.29771209, 0.        ,
         0.4624    , 0.39145563])),
 ('man bites dog. god loves man',
  array([0.        , 0.        , 0.36580076, 0.28407693, 0.        ,
         0.48098405, 0.        , 0.        , 0.        , 0.48098405,
         0.56815385, 0.        ])),
 ('Dog and man are friends. dog is kind man',
  array([0.3793921 , 0.3793921 , 0.        , 0.44815017, 0.3793921 ,
         0.        , 0.        , 0.28853747, 0.28853747, 0.        ,
         0.44815017, 0.        ]))]

#### as per tf ,idf formula--- idf is fixed. tf changes for each doc and so is tf*idf


In [591]:
!pip install patool
import patoolib
patoolib.extract_archive("aclImdb_v1.tar.gz")



PatoolError: file `aclImdb_v1.tar.gz' was not found